// Generated by CoffeeScript 1.3.2
var Config;

Config = (function() {

  function Config() {}

  Config.PROXY_IMAGE_URL = 'http://www.google.com/puppies.jpg';

  Config.SCROLL_SENSITIVITY = .001;

  Config.PAN_SENSITIVITY = 0.005;

  Config.UPPER_SCROLL_LIMIT = 0.95033;
  return Config;

})();
